name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codes
        uses: actions/checkout@v7

      - name: Run cargo fmt
        shell: bash
      - run: cargo fmt --all --check

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codes
        uses: actions/checkout@v7

      - name: Run cargo clippy
        shell: bash
        run: cargo clippy --all-features -- -D warnings

  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        features:
          - ""
          - "backend-openai"
          - "backend-azure"
          - "backend-bedrock"
          - "backend-vertex"
          - "all"
    steps:
      - name: Checkout codes
        uses: actions/checkout@v7

      - name: Run tests
        run: |
          if [ "${{ matrix.features }}" = "all" ]; then
            cargo test --all-features
          elif [ -z "${{ matrix.features }}" ]; then
            cargo test --no-default-features
          else
            cargo test --no-default-features --features "${{ matrix.features }}"
          fi

